stack_underflow/urls.py
from django.urls import path, include
from stack_underflow import views
app_name = 'stack_underflow'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_thread/', views.add_thread, name='add_thread'),
    path('category/<slug:thread_question_slug>/show_thread/', views.show_thread, name='show_thread'),
    path('category/<slug:thread_question_slug>/add_reply/', views.add_reply, name='add_reply'),
    path('categories/', views.categories, name='categories'),
    path('add_category/', views.add_category, name='add_category'),
    path('logout/', views.user_logout, name='logout'),
    path('register_profile/', views.register_profile, name='register_profile'),
]

stackunderflow/urls.py
from django.contrib import admin
from django.urls import path
from stack_underflow import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

wad2project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse
from registration.backends.simple.views import RegistrationView
from stack_underflow import views

class MyRegistrationView(RegistrationView):
    def get_success_url(selfself, user):
        return reverse('stack_underflow:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('stack_underflow/', include('stack_underflow.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stack_underflow/models.py
from django.db import models, IntegrityError
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', primary_key=True, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True, default='logo2.png')

    def __str__(self):
        return self.user.username

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, unique=True)
    threads = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Thread(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    question = models.CharField(max_length=128, unique=True)
    replies = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    #url = models.URLField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.question)
        super(Thread, self).save(*args, **kwargs)

    def __str__(self):
        return self.question

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    text = models.CharField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Replies'

    def save(self, *args, **kwargs):
        super(Reply, self).save(*args, **kwargs)

    def __str__(self):
        return self.text

stack_underflow/forms.py
from django import forms
from django.contrib.auth.models import User
from stack_underflow.models import Category, Thread, Reply, UserProfile

class Sign_Up_Form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class ThreadForm(forms.ModelForm):

    question = forms.CharField(max_length=128,
                               help_text="Please enter a question")
    replies = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Thread
        fields = ('question',)

class ReplyForm(forms.ModelForm):
    text = forms.CharField(max_length=2000,
                           help_text='Please enter a reply')


    class Meta:
        model = Reply
        fields = ('text',)

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('picture',)

stack_underflow/views.py
from django.shortcuts import render
from django.http import HttpResponse
from stack_underflow.models import Category
from stack_underflow.models import Thread
from stack_underflow.models import Reply
from django.shortcuts import redirect
from django.shortcuts import reverse
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from stack_underflow.bing_search import run_query
from stack_underflow.forms import UserProfileForm, Sign_Up_Form, CategoryForm, ReplyForm, ThreadForm
from stack_underflow.models import Category


def index(request):
    category_list = Category.objects.order_by('-threads')[:5]
    threads_list = Thread.objects.order_by('-replies')[:5]
    context_dict = {}
    context_dict['categories'] = category_list
    context_dict['threads'] = threads_list
    return render(request, 'stack_underflow/index.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        sign_Up_form = Sign_Up_Form(request.POST)
        profile_form = UserProfileForm(request.POST)

        if sign_Up_form.is_valid() and profile_form.is_valid():
            user = sign_Up_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
        else:
            print(sign_Up_form.errors, profile_form.errors)
    else:
        sign_Up_form = Sign_Up_Form()
        profile_form = UserProfileForm()

    return render(request, 'stack_underflow/registration_form.html',
                  context = {'sign_Up_Form': sign_Up_form,
                             'profile_form': profile_form,
                             'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('stack_underflow:index'))
            else:
                return HttpResponse("Your StackUnderflow account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'stack_underflow/login.html')

def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        threads = Thread.objects.filter(category=category)
        context_dict['threads'] = threads
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['threads'] = None

    return render(request, 'stack_underflow/category.html', context=context_dict)

def show_thread(request, thread_question_slug):
    context_dict = {}

    try:
        thread = Thread.objects.get(slug=thread_question_slug)
        replies = Reply.objects.filter(thread=thread)
        context_dict['replies'] = replies
        context_dict['thread'] = thread
    except Thread.DoesNotExist:
        context_dict['replies'] = None
        context_dict['thread'] = None

    return render(request, 'stack_underflow/thread.html', context=context_dict)



@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('stack_underflow:index'))


def categories(request):
    context_dict = {}
    category_list = Category.objects.order_by('-threads')[:]
    threads_list = Thread.objects.order_by('-replies')[:5]
    context_dict = {}
    context_dict['categories'] = category_list
    context_dict['threads'] = threads_list


    return render(request, 'stack_underflow/categories.html', context=context_dict)



@login_required
def add_category(request):

    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            cat = form.save(commit=False)
            cat.user = request.user
            cat.threads = cat.threads + 1
            cat.save()
            return redirect(reverse('stack_underflow:categories'))
        else:
            print(form.errors)

    return render(request, 'stack_underflow/add_category.html', {'form' : form})

@login_required
def add_thread(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if cat is None:
        return redirect('stack_underflow:index')

    form = ThreadForm()

    if request.method == 'POST':
        form = ThreadForm(request.POST)
        if form.is_valid():
            if cat:
                t = form.save(commit=False)
                t.category = cat
                t.replies = t.replies + 1
                t.user = request.user
                t.save()
                return redirect(reverse('stack_underflow:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': cat}
    return render(request, 'stack_underflow/add_thread.html', context=context_dict)




@login_required
def add_reply(request, thread_question_slug):

    try:
        thread = Thread.objects.get(slug=thread_question_slug)
    except Thread.DoesNotExist:
        thread = None

    if thread is None:
        return redirect('stack_underflow:index')

    form = ReplyForm()

    if request.method == 'POST':
        form = ReplyForm(request.POST)

        if form.is_valid():
            if thread:
                reply = form.save(commit=False)
                reply.thread = thread
                reply.user = request.user
                reply.save()

                return redirect(reverse('stack_underflow:show_thread', kwargs={'thread_question_slug': thread_question_slug}))

        else:
            print(form.errors)

    context_dict = {'form': form, 'thread': thread}
    return render(request, 'stack_underflow/add_reply.html', context=context_dict)

@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect(reverse('stack_underflow:index'))
        else:
            print(form.errors)
    context_dict = {'form': form}
    return render(request, 'stack_underflow/profile_registration.html', context_dict)



def search(request):
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            results = run_query(query)
            result_list = results[0]
            result_cat = results[1]
            result_thr = results[2]

    return render(request, 'stack_underflow/search.html', {'result_list': result_list, 'result_cat': result_cat, 'result_thr': result_thr})

templates/stack_underflow/add_category.html
<!DOCTYPE html>
{%extends 'stack_underflow/base.html' %}
{%load staticfiles %}

<html>
<head>
    {% block title_block %}
        Add a Category
    {% endblock %}
</head>
{% block body_block %}
   <div class="jumbotron text-left">
    <h1>Add a Category</h1>
    </div>
    <div>
        <form id="category_form" method="post" action="/stack_underflow/add_category/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
           <button class="btn btn-outline-dark" type="submit" value="Submit">Create Category</button>
        </form>
    </div>
{% endblock %}

templates/stack_underflow/add_reply.html
<!DOCTYPE html>
{% extends 'stack_underflow/base.html' %}
{%load staticfiles %}

<head>
    {% block title_block %}
    {% if reply %}
        {{ reply.thread }}
    {% else %}
        Unknown
    {% endif %}
    {% endblock %}
</head>

{% block body_block %}
    <div class="jumbotron text-left">
        <h1>Add Reply</h1>
    </div>
        <form id="reply_form" method="post" action="/stack_underflow/category/{{ thread.slug }}/add_reply/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <button class="btn btn-outline-dark" type="submit" value="Submit">Reply</button>
        </form>
    </div>
{% endblock %}

templates/stack_underflow/add_thread.html
{% extends 'stack_underflow/base.html' %}
{% load staticfiles %}

<title>
{% block title_block %}
    Add a Thread
{% endblock %}
</title>

{% block body_block %}
    <div class="jumbotron text-left">
        <h1>Add thread to {{ category.name }}</h1>
    </div>
        <div>
            <form role="form" id="page_form" method="post" action="/stack_underflow/category/{{ category.slug }}/add_thread/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <button class="btn btn-outline-dark" type="submit" value="Submit">Add Thread</button>
            </form>
        </div>
{% endblock %}

templates/stack_underflow/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title_block %}
        Welcome to StackUnderflow
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- CSS Styles for templates -->
    <link href="{% static 'css/stack_underflow.css' %}" rel="stylesheet">
</head>

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top p-0" style="background-color: #ff5800;">
        <a class="navbar-brand p-2" href="{% url 'stack_underflow:index' %}"><img src="{% static 'images/logo1.png' %}"
                                                                                  width="50" height="" 50"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link active" href="{% url 'stack_underflow:index' %}">Home</a></li>
                <li class="nav-item "><a class="nav-link active" href="{% url 'stack_underflow:categories' %}">Categories</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active"
                                        href="{% url 'auth_logout' %}?next={% url 'stack_underflow:index' %}">Logout</a>
                </li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'stack_underflow:add_category' %}">Add
                    Category</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'auth_password_change' %}">Change
                    Password</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" href="{% url 'registration_register' %}">Register
                    Here</a></li>
                <li class="nav-item "><a class="nav-link active" href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0" id="user-form" method="post" action="{% url 'stack_underflow:search' %}">
                {% csrf_token %}
                <div class="form-group mx-sm-3 mb-2">
                <input class="form-control mr-sm-2" type="text" name="query" id="query" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit" name="submit">Search</button>
                </div>
            </form>
        </div>
    </nav>
</header>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                {% block sidebar_block %}
                {% endblock %}
            </div>
        </nav>
    </div>
</div>

<main class="col-md-9 mt-4 ml-sm-auto col-lg-10 px-6" role="main">
    <body>
    {% block body_block %}
    {% endblock %}
    </body>
    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted"><a class="" float-left">&copy; 2020 StackUnderflow &middot; <a href="#">About</a> &middot;</span>
        </div>
    </footer>
</main>

</html>

templates/stack_underflow/categories.html
<!DOCTYPE html>
{%extends 'stack_underflow/base.html' %}
{%load staticfiles %}

<html>
<head>
    <title>Categories</title>
</head>
{% block body_block %}


<div class="jumbotron text-center">
    <h1>Categories</h1>
    <p class="lead text-muted">Hopefully, you can find a category you are looking for, if not why not add your
        own?</p>
</div>

<div class="container">
    {% if categories %}

    {% for category in categories %}
    <div class="card-body bg-dark">
        <h5 class="card-title text-white">{{ category.name }}</h5>
        <a href="{% url 'stack_underflow:show_category' category.slug %}" class="btn btn-outline-light">Go</a>
    </div>
    <br>
    {% endfor %}

    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
</div>
<br>
<div class="card" style="background-color: #f77959; border-color: #f77959;">
    <div class="text-white">
        <div class="card-body">
            <h5 class="card-title"></h5>
            <p>Can't find the category you are looking for....</p>
            <a class="btn btn-outline-light" href="{% url 'stack_underflow:add_category' %}">Add Category</a>
        </div>
    </div>
</div>

{% endblock %}

</html>

templates/stack_underflow/category.html
<!DOCTYPE html>
{% extends 'stack_underflow/base.html' %}
{% load staticfiles %}

<title>
{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}
</title>

{% block body_block %}
    {% if category %}
    <div class="jumbotron text-left">
        <h1>{{ category.name }}</h1>
    </div>
    {% if threads %}
    <ul>
        {% for thread in threads %}
        <div class="card-body card-body-index py-3">
            <div class="row no-gutters align-items-center">
                <div class="col"> <a href="{% url 'stack_underflow:show_thread' thread.slug %}" class="text-big" data-abc="true">{{ thread.question }}</a>
                    <div class="text-muted small mt-1">{{ thread.created_at }}<a href="javascript:void(0)" class="text-muted" data-abc="true"></a></div>
                </div>
                <div class="d-none d-md-block col-4">
                    <div class="row no-gutters align-items-center">
                        <div class="col-4">
                            <p>  Replies:</p>
                            <span class="badge badge-dark badge-pill">{{ thread.replies }}</span>
                        </div>
                        <div class="media col-8 align-items-center">
                            {% if thread.user.profile.picture %}
                                <img src="{{ thread.user.profile.picture.url }}" class="d-block ui-w-30 rounded-circle" width="50" height="50">
                            {% else %}
                                <img src="{% static 'images/logo2.png' %}" class="d-block ui-w-30 rounded-circle" width="50" height="50">
                            {% endif %}
                            <div class="media-body flex-truncate ml-2">
                                <div class="line-height-1 text-truncate">by {{ thread.user }}</div> <a href="javascript:void(0)" class="text-muted small text-truncate" data-abc="true"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-outline-dark" href="{% url 'stack_underflow:add_thread' category.slug %}" role="button">Add Thread</a> <br />
        {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/stack_underflow/index.html
<!DOCTYPE html>
{%extends 'stack_underflow/base.html' %}
{%load staticfiles %}

<html>
<head>
    <title>StackUnderflow</title>
</head>
{% block body_block %}

<div class="text-center mb-4">
    <img class="mt-4" src="{% static 'images/logo.jpg' %}" alt="" width="300" height="120">
</div>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
      {% if user.is_authenticated %}
            <h1 class="display-4">Welcome to StackUnderflow,</h1>
            <h1>{{ user.username }}</h1>
      {% else %}
            <h1 class="display-4">Welcome to StackUnderflow</h1>
      {% endif %}
            <p class="lead">The place to find the answers to all your questions.</p>
  </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6" style="background-color: #e0e0e0; border-color: #e0e0e0;">
                <div class="card-body">
                    <h2>Most Popular Categories</h2>
                    <p class="card-text">
                        {% if categories %}
                    <ul>
                        {% for category in categories %}
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                     <a href="{% url 'stack_underflow:show_category' category.slug %}"> {{ category.name }}</a>
                                    <span class="badge badge-dark badge-pill">{{ category.threads }}</span>
                                </li>
                            </ul>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no categories present.</strong>
                    {% endif %}
                    </p>
                    <a class="btn btn-outline-dark" href="{% url 'stack_underflow:categories' %}" role="button">Show all Categories</a>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card mb-6" style="background-color: #e0e0e0; border-color: #e0e0e0;">
                <div class="card-body">
                    <h2>Most Popular Threads</h2>
                    <p class="card-text">
                        {% if categories %}
                    <ul>
                        {% for thread in threads %}
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                     <a href="{% url 'stack_underflow:show_thread' thread.slug %}">{{ thread.question }}</a>
                                    <div class="text-muted small mt-1">{{ thread.category }}<a href="" class="text-muted" data-abc="true"></a></div>
                                    <span class="badge badge-dark badge-pill">{{ thread.replies }}</span>
                                </li>
                            </ul>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no threads present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</html>

templates/stack_underflow/profile_registration.html
{% extends 'stack_underflow/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register - Create Profile
{% endblock %}
{% block body_block %}
<div class="jumbotronp-4">
    <div class="container">
        <h1 class="jumbotron-heading">Register Here - Create Profile</h1>
    </div>
</div>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <div class="card mb-4" style="background-color: #e0e0e0; border-color: #e0e0e0;">
                <div class="card-body">
                    <div class="form-group">
                        <div class="text-center mb-4">
                            <form method="post" action="{% url 'stack_underflow:register_profile' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                             <input type="submit" value="Create Profile" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/stack_underflow/search.html
<!DOCTYPE html>
{% extends 'stack_underflow/base.html' %}
{% load staticfiles %}


{% block title_block %}
Search
{% endblock %}


{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Search results</h1>
    </div>
</div>
<div>
    {% if result_cat %}
    <br>
    <h2>Categories</h2>
    <div class="list-group">
        {% for result in result_cat %}
        <div class="list-group-item">
            <h3 class="list-group-item-heading">
                <a href="{{ result.link }}">
                    {{ result.title|safe|escape }}
                </a>
            </h3>
            <p class="list-group-item-text">
                {{ result.summary|safe|escape }}
            </p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<br>
<div>
    {% if result_thr %}
    <br>
    <h2>Threads</h2>
    <div class="list-group">
        {% for result in result_thr %}
        <div class="list-group-item">
            <h3 class="list-group-item-heading">
                <a href="{{ result.link }}">
                    {{ result.title|safe|escape }}
                </a>
            </h3>
            <p class="list-group-item-text">
                {{ result.summary|safe|escape }}
            </p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<br>
<div>
    {% if result_list %}
    <h1>Web Results</h1>
    <div class="list-group">
        {% for result in result_list %}
        <div class="list-group-item">
            <h3 class="list-group-item-heading">
                <a href="{{ result.link }}">
                    {{ result.title|safe|escape }}
                </a>
            </h3>
            <p class="list-group-item-text">
                {{ result.summary|safe|escape }}
            </p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

templates/stack_underflow/thread.html
<!DOCTYPE html>
{% extends 'stack_underflow/base.html' %}
{% load staticfiles %}

<title>
{% block title_block %}
    {% if thread %}
        {{ thread.question }}
    {% else %}
        No thread present.
    {% endif %}
{% endblock %}
</title>

{% block body_block %}
    {% if thread %}
    <div class="mt-4">
       <h1>{{ thread.question }}</h1>
    </div>
    {% if thread %}
    <ul>
        {% for reply in replies %}
        <div class="card-body card-body-index py-3">
            <div class="row no-gutters align-items-center">
                <div class="col">
                    <p>{{ reply.text }}</p>
                </div>
                <div class="d-none d-md-block col-4">
                    <div class="row no-gutters align-items-center">
                        <div class="media col-8 align-items-center">
                            {% if reply.user.profile.picture %}
                                <img src="{{ reply.user.profile.picture.url }}" class="d-block ui-w-30 rounded-circle" width="50" height="50">
                            {% else %}
                                <img src="{% static 'images/logo2.png' %}" class="d-block ui-w-30 rounded-circle" width="50" height="50">
                            {% endif %}
                            <div class="media-body flex-truncate ml-2">
                                <div class="line-height-1 text-truncate">{{ reply.created_at }}</div> <a href="javascript:void(0)" class="text-muted small text-truncate" data-abc="true">by {{ reply.user.username }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No replies, be the first to reply to this question...</strong>
    {% endif %}
		{% if user.is_authenticated %}
    		<a href="/stack_underflow/category/{{ thread.slug }}/add_reply/" class="btn btn-outline-dark">Add a Reply</a> <br />
		{% endif %}
    {% else %}
    	The specified thread does not exist.
    {% endif %}
{% endblock %}